# =======================================================
# PORTAINER STACK - FINGERPRINT MEDIA CONVERTER v1.0
# =======================================================
# Cole este arquivo no Portainer > Stacks > Add Stack
# =======================================================

version: '3.8'

services:
  fingerprint-converter:
    image: jondevsouza31/fingerprint-converter:latest
    container_name: fingerprint-converter
    ports:
      - "5001:5001"
    environment:
      # Server Configuration
      - PORT=5001
      - APP_ENV=production
      - READ_TIMEOUT=5m
      - WRITE_TIMEOUT=5m
      - BODY_LIMIT=524288000
      
      # Performance Tuning
      - GOMEMLIMIT=2GiB
      - GOGC=100
      - MAX_WORKERS=64
      - BUFFER_POOL_SIZE=100
      - BUFFER_SIZE=10485760
      - REQUEST_TIMEOUT=5m
      - DOWNLOAD_TIMEOUT=30s
      - MAX_DOWNLOAD_SIZE=524288000
      
      # Cache Configuration (28/30 minutos)
      - CACHE_DIR=/data/fingerprintconverter
      - CACHE_TTL=28m
      - FILE_TTL=30m
      - ENABLE_CACHE=true
      
      # Anti-Fingerprint Settings
      - DEFAULT_AF_LEVEL=moderate
      
      # Logging
      - LOG_LEVEL=info
      - ENABLE_PERFORMANCE_LOGS=true
      - DEBUG=false
      
      # Production Settings
      - PRODUCTION_MODE=true
      - ENABLE_CORS=true
      
      # Monitoring
      - ENABLE_HEALTH_CHECK=true
      - ENABLE_STATS_ENDPOINT=true
    
    # Volume persistente organizado por tipo de mídia
    volumes:
      - fingerprint-data:/data/fingerprintconverter
    
    restart: always
    
    # Use a mesma rede da sua API Node.js
    networks:
      - whatsapp-network
    
    # Limits de recursos (ajuste conforme sua VPS)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  whatsapp-network:
    driver: bridge

volumes:
  fingerprint-data:
    driver: local

# =======================================================
# ENDPOINTS DA API
# =======================================================
# POST http://SEU_IP:5001/api/convert
# GET  http://SEU_IP:5001/api/health
# GET  http://SEU_IP:5001/api/cache/stats
# GET  http://SEU_IP:5001/api/cache/stats/:deviceID
#
# DOCUMENTAÇÃO COMPLETA:
# https://github.com/jonemp31/fingerprint-converter
# =======================================================

# =======================================================
# INTEGRAÇÃO SIMPLIFICADA
# =======================================================
# A API agora detecta automaticamente:
# - Tipo de mídia pela extensão (.mp3=audio, .jpg=image, .mp4=video)
# - Nível AF ideal (audio=moderate, image=moderate, video=basic)
# - Organiza em pastas: /data/fingerprintconverter/{audios,imagens,videos}
#
# Exemplo mínimo (só device_id e url):
# curl -X POST http://localhost:5001/api/convert \
#   -H "Content-Type: application/json" \
#   -d '{"device_id":"cel01","url":"https://example.com/audio.mp3"}'
#
# Com download direto:
# curl -X POST "http://localhost:5001/api/convert?download=true" \
#   -H "Content-Type: application/json" \
#   -d '{"device_id":"cel01","url":"https://example.com/audio.mp3"}' \
#   -o output.opus
# =======================================================

# =======================================================
# AJUSTES DE PERFORMANCE
# =======================================================
# VPS com 2 CPU, 2GB RAM:
#   MAX_WORKERS: 32
#   BUFFER_POOL_SIZE: 50
#   tmpfs: size=2G
#   limits: cpus: '2', memory: 2G
#
# VPS com 4 CPU, 4GB RAM (padrão):
#   MAX_WORKERS: 64
#   BUFFER_POOL_SIZE: 100
#   tmpfs: size=4G
#   limits: cpus: '4', memory: 4G
#
# VPS com 8+ CPU, 8GB+ RAM:
#   MAX_WORKERS: 128
#   BUFFER_POOL_SIZE: 150
#   tmpfs: size=8G
#   limits: cpus: '8', memory: 8G
# =======================================================

# =======================================================
# NÍVEIS DE ANTI-FINGERPRINTING RECOMENDADOS
# =======================================================
# Audio: moderate (melhor custo/benefício)
# Imagem: moderate (noise adaptativo para PNG)
# Vídeo: basic (evita aumento excessivo de tamanho)
#
# Use 'paranoid' apenas para volumes muito altos
# =======================================================

# =======================================================
# PRONTO PARA COPIAR E COLAR NO PORTAINER!
# =======================================================
